services:
  traefik:
    image: traefik:v3.3.4  # Note: Verify version; latest is v2.10.5 as of now
    container_name: traefik
    restart: always
    ports:
      - '80:80'
      - '443:443'
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.tls=true'
      - '--entrypoints.websecure.http.tls.certresolver=myresolver'
      # ACME (Let’s Encrypt)
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=${SSL_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      # Logging
      - '--log.level=DEBUG'
      # Enable Prometheus metrics
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.addEntryPointsLabels=true'
      - '--metrics.prometheus.addRoutersLabels=true'
      - '--metrics.prometheus.addServicesLabels=true'
      - '--metrics.prometheus.entryPoint=metrics'
      - '--entrypoints.metrics.address=:8082'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls=true'
      - 'traefik.http.routers.dashboard.tls.certresolver=myresolver'
      - 'traefik.http.routers.dashboard.service=api@internal'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt
    networks:
      - traefik

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.prometheus.entrypoints=websecure'
      - 'traefik.http.routers.prometheus.tls=true'
      - 'traefik.http.routers.prometheus.tls.certresolver=myresolver'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
    networks:
      - traefik

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change for security
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - '3001:3000'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.grafana.entrypoints=websecure'
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.tls.certresolver=myresolver'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'  # Internal port
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    driver: bridge

volumes:
  traefik_data:
  grafana-data:
